language: generic

jdk:
  - openjdk8
  - oraclejdk8

python:
  - "2.7"

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  # boot repeater console
  - cd ./analysis/python2.x
  - python setup.py install --user
  - cd -

after_success:
  - mvn clean install cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)